### ISSUE TITLE
"Object reference not set to an instance of an object" when trying to save PAL savefile as other region

### ISSUE THREAD

**Issue by Resident007** [Nenkai/GT4SaveEditor#1]
When I try to save my old PAL region save to any other region, it just throws me "Object reference not set to an instance of an object" without actually saying me what's wrong. I understand that this feature may break the game (especially if a large save is used like mine with 100% completion), but it seems like it doesn't even want to save files to the folder I specify, it just creates a folder (named BASCUS-97328GAMEDATA if I try to save as NTSC-U), but throws an error and doesn't do anything beyond that.

![image](https://user-images.githubusercontent.com/25570319/229563474-cf51df8f-2981-4c03-9e82-47f629b7bd7d.png)

I am also attaching the link to my save files, in case it helps: https://drive.google.com/file/d/1cJUYpFe2kPkRzVCIZRfgGHKsaBJGT1JO/view?usp=share_link

**Comment by Nenkai** [comment]
Thanks;
Retest with 0.5.1

**Comment by Resident007** [comment]
Thank you for such a fast reaction, now it worked like a charm! Was able to convert my huge 100% save to NTSC-U region successfully. Keep up the great work!
