### ISSUE TITLE
Crash when trying to open "Garage" tab of a converted savefile

### ISSUE THREAD

**Issue by Resident007** [Nenkai/GT4SaveEditor#2]
Following #1: Now I successfully loaded into the NTSC-U version of GT4 using the save file converted from PAL, but I was getting "Game data is corrupted. Do you wish to retry?" message every time I tried to get into any car other than the car I currently was, and some of the entries in the garage were blank. However, when I tried to open up the garage of a converted save folder, GT4 Save Editor just crashed without telling me the reasons. Being a software tester, I imagine it has to either at least give the user some clue about the reason of the crash or handle the car data mismatch in another way (ideally, removing all incompatible cars automatically).

**Comment by Nenkai** [comment]
I don't currently own anything but the PAL version, but converting your save to GT4 Online US worked fine.

Blank cars are normal; they're seperate car entries in each region for localization purposes, so the game is unable to determine which car it is and will accordingly crash (as implied in the warning message).

Other cars however I expected to work; When converting from only the region and not GT4<->GT4O, the garage should load up fine. It appears not to be the case so i'll look it up when possible.

**Comment by Resident007** [comment]
> I don't currently own anything but the PAL version, but converting your save to GT4 Online US worked fine.
> 
> Blank cars are normal; they're seperate car entries in each region for localization purposes, so the game is unable to determine which car it is and will accordingly crash (as implied in the warning message).
> 
> Other cars however I expected to work; When converting from only the region and not GT4<->GT4O, the garage should load up fine. It appears not to be the case so i'll look it up when possible.

What I did now to prevent crash of the Save Editor is: I compared my garage in PAL and NTSC-U versions, and manually removed (from the PAL save) all the cars that are not compatible **prior** to converting it to NTSC-U. Now the Save Editor loads the Garage tab without any problem, but another one arose: Any cars that I never drove on the PAL version can be opened and driven in NTSC version. But, if the car was driven at least once in PAL version (so "Has Data" in Save Editor) is True, I again get "Game Data is corrupted" while trying to "board" it on the NTSC version, so it seems like a some sort of incompatibility in car data that needs additional conversion or something. Might be related to shuffling during decryption that you mentioned in readme though.

**Comment by Nenkai** [comment]
Retest w/ 0.6.0

**Comment by Resident007** [comment]
As of 0.6.0, Save Editor no longer crashes under the conditions above and the game now correctly loads all the cars and lets me ride them. Of course the game will just freeze if I try to ride any car that is shown as blank entry in Garage, but this is quite expected behavior and it's not difficult for me to remove these cars from the save file. Thank you!

**Comment by nekotogd** [comment]
Tried opening Garage tab of an NTSC-U save in v0.6.3 and it crashed the editor.

However, it opens and seems to work fine in v0.6.0
